URL = "https://apis.codante.io/olympic-games/countries"
TOTAL_RESULTS = 50

TRANSLATIONS = {
    '3x3 Basketball': 'Basquete 3x3',
    'Archery': 'Tiro com Arco',
    'Artistic Gymnastics': 'Ginástica Artística',
    'Artistic Swimming': 'Nado Artístico',
    'Athletics': 'Atletismo',
    'Badminton': 'Badminton',
    'Basketball': 'Basquete',
    'Beach Volleyball': 'Vôlei de Praia',
    'Boxing': 'Boxe',
    'Breaking': 'Breaking',
    'Canoe Slalom': 'Canoagem Slalom',
    'Canoe Sprint': 'Canoagem Velocidade',
    'Cycling BMX Freestyle': 'Ciclismo BMX Freestyle',
    'Cycling BMX Racing': 'Ciclismo BMX Racing',
    'Cycling Mountain Bike': 'Ciclismo Mountain Bike',
    'Cycling Road': 'Ciclismo de Estrada',
    'Cycling Track': 'Ciclismo de Pista',
    'Diving': 'Saltos Ornamentais',
    'Equestrian': 'Hipismo',
    'Fencing': 'Esgrima',
    'Football': 'Futebol',
    'Golf': 'Golfe',
    'Handball': 'Handebol',
    'Hockey': 'Hóquei sobre Grama',
    'Judo': 'Judô',
    'Marathon Swimming': 'Maratona Aquática',
    'Modern Pentathlon': 'Pentatlo Moderno',
    'Rhythmic Gymnastics': 'Ginástica Rítmica',
    'Rowing': 'Remo',
    'Rugby Sevens': 'Rugby Sevens',
    'Sailing': 'Vela',
    'Shooting': 'Tiro Esportivo',
    'Skateboarding': 'Skate',
    'Sport Climbing': 'Escalada Esportiva',
    'Surfing': 'Surfe',
    'Swimming': 'Natação',
    'Table Tennis': 'Tênis de Mesa',
    'Taekwondo': 'Taekwondo',
    'Tennis': 'Tênis',
    'Trampoline Gymnastics': 'Ginástica de Trampolim',
    'Triathlon': 'Triatlo',
    'Volleyball': 'Voleibol',
    'Water Polo': 'Polo Aquático',
    'Weightlifting': 'Levantamento de Peso',
    'Wrestling': 'Luta Olímpica'
}
